coding ...

diff --git a/bin/iving_dns_learnaddr b/bin/iving_dns_learnaddr
--- a/bin/iving_dns_learnaddr
+++ b/bin/iving_dns_learnaddr
@@ -1,88 +1,90 @@
-#!/bin/sh
-# openvpn learn-address script to manage a hosts-like file
-# - intended to allow dnsmasq to resolve openvpn clients
-#   addn-hosts=/etc/hosts.openvpn-clients
-# - written for openwrt (busybox), but should work most anywhere
+#!/bin/bash
 #
 # Changelog
 # 2006-10-13 BDL original
+# 2013-21-10 - Do not use absolute paths, to be more cross compatible
+#            - Add support for flock locking
 
-# replace with a sub-domain of your domain, use a sub-domain to
-# prevent VPN clients from stealing existing names
-DOMAIN=vpn.example.net
+PATH=$PATH:/bin:/usr/bin
 
-HOSTS=/etc/hosts.openvpn-clients
-
-h=$(/usr/bin/basename "$HOSTS")
-LOCKFILE="/var/run/$h.lock"
+# replace with a sub-domain of your domain, use a sub-domain to prevent VPN clients from stealing existing names
+DOMAIN=${DOMAIN:-"vpn.example.net"}
+HOSTS=${HOSTS:-"/etc/hosts.openvpn-clients"}
+LOCKFILE=${LOCKFILE:-"/var/run/$(basename "$HOSTS").lock"}
+DNSMASQ=${DNSMASQ:-"/var/run/dnsmasq.pid"}
 
 IP="$2"
 CN="$3"
 
 case "$1" in
-   add|update)
-     if [ -z "$IP" -o -z "$CN" ]; then
-         echo "$0: IP and/or Common Name not provided" >&2
-         exit 0
-     fi
-   ;;
-   delete)
-     if [ -z "$IP" ]; then
-         echo "$0: IP not provided" >&2
-         exit 0
-     fi
-   ;;
+  add|update)
+    if [ -z "$IP" -o -z "$CN" ]; then
+        echo "$0: IP and/or Common Name not provided" >&2
+        exit 0
+    fi
+  ;;
+  delete)
+    if [ -z "$IP" ]; then
+        echo "$0: IP not provided" >&2
+        exit 0
+    fi
+  ;;
    *)
-     echo "$0: unknown operation [$1]" >&2
-     exit 1
-   ;;
+    echo "$0: unknown operation [$1]" >&2
+    exit 1
+  ;;
 esac
 
 
-# serialise concurrent accesses
-[ -x /bin/lock ] && /bin/lock "$LOCKFILE"
-
 # clean up IP if we can
-[ -x /bin/ipcalc ] && eval $(ipcalc "$IP")
+command -v ipcalc >/dev/null 2>&1 && eval $(ipcalc -n "$IP")
 
 FQDN="$CN.$DOMAIN"
 
-# busybox mktemp must have exactly six X's
-t=$(/bin/mktemp "/tmp/$h.XXXXXX")
-if [ $? -ne 0 ]; then
-     echo "$0: mktemp failed" >&2
-     exit 1
-fi
+(
+  # Busybox uses lock instead of flock so choose the correct implementation
+  (command -v flock >/dev/null 2>&1 && (flock -x 200)) ||
+  (command -v lock >/dev/null 2>&1 && (lock "$LOCKFILE"))
 
+  # busybox mktemp must have exactly six X's
+  t=$(mktemp "/tmp/$h.XXXXXX")
+  if [ $? -ne 0 ]; then
+      echo "$0: mktemp failed" >&2
+      exit 1
+  fi
 
-case "$1" in
+  # Try to create hosts file if it does not exist yet
+  [ ! -f $HOSTS ] && touch $HOSTS
 
-   add|update)
-     /usr/bin/awk '
-         # update/uncomment address|FQDN with new record, drop any
-duplicates:
-         $1 == "'"$IP"'" || $1 == "#'"$IP"'" || $2 == "'"$FQDN"'" \
-             { if (!m) print "'"$IP"'\t'"$FQDN"'"; m=1; next }
-         { print }
-         END { if (!m) print "'"$IP"'\t'"$FQDN"'" }           # add
-new address to end
-     ' "$HOSTS" > "$t" && cat "$t" > "$HOSTS"
-   ;;
+  case "$1" in
 
-   delete)
-     /usr/bin/awk '
-         # no FQDN, comment out all matching addresses (should only
-be one)
-         $1 == "'"$IP"'" { print "#" $0; next }
-         { print }
-     ' "$HOSTS" > "$t" && cat "$t" > "$HOSTS"
-   ;;
+    add|update)
+      awk '
+          # update/uncomment address|FQDN with new record, drop any duplicates:
+          $2 == "'"$FQDN"'" \
+              { if (!m) print "'"$IP"'\t'"$FQDN"'"; m=1; next }
+          { print }
+          END { if (!m) print "'"$IP"'\t'"$FQDN"'" }           # add new address to end
+      ' "$HOSTS" > "$t" && cat "$t" > "$HOSTS"
+    ;;
 
-esac
+    delete)
+      awk '
+          # no FQDN, comment out all matching addresses (should only be one)
+          $1 == "'"$IP"'" { print "#" $0; next }
+          { print }
+      ' "$HOSTS" > "$t" && cat "$t" > "$HOSTS"
+    ;;
+
+  esac
+
+  rm "$t"
+
+  # Busybox uses lock instead of flock so choose the correct implementation
+  (command -v flock >/dev/null 2>&1 && false) ||
+  (command -v lock >/dev/null 2>&1 && (lock -u "$LOCKFILE"))
+) 200>$((command -v flock >/dev/null 2>&1 && (echo $LOCKFILE)) ||
+        (command -v lock >/dev/null 2>&1 && (echo "/dev/null")))
 
 # signal dnsmasq to reread hosts file
-/bin/kill -HUP $(cat /var/run/dnsmasq.pid)
-
-/bin/rm "$t"
-
-[ -x /bin/lock ] && /bin/lock -u "$LOCKFILE"
+[ -f $DNSMASQ ] && kill -HUP $(cat $DNSMASQ)
